ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_kapak JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_oz JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_abstract JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_onsoz JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_ekler JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_kisaltmalar JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tiptap_icindekiler JSONB;
